### ISSUE TITLE
Bug: Robot removed from portal

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtecharchive/0-robot-portal#4]
After checking the portal again we found that the robot registered using a template was not registered in the portal anymore.

![image](https://user-images.githubusercontent.com/23582741/45285932-c6768780-b4e4-11e8-9437-a1cb3e5a84f4.png)

Found this eco but don't know if related.
![image](https://user-images.githubusercontent.com/23582741/45286066-1b1a0280-b4e5-11e8-9d84-ae928ad81fe1.png)

When scheduling the uninstall action I get a 500 status back from the portal
```
----> 1 s.schedule_action("uninstall", args={'username':'<username>','password':'<password>'}).wait(die=True).state

/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py in wait(self, timeout, die)
    123                 raise TimeoutError()
    124         else:
--> 125             wait()
    126 
    127         if die is True and self.state == TASK_STATE_ERROR:

/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py in wait()
    112         """
    113         def wait():
--> 114             while self.state in ('new', 'running'):
    115                 gevent.sleep(0.5)
    116 

/opt/code/github/threefoldtech/0-robot/zerorobot/service_proxy.py in state(self)
    170     @property
    171     def state(self):
--> 172         task, _ = self.service._zrobot_client.api.services.GetTask(task_guid=self.guid, service_guid=self.service.guid)
    173         return task.state.value
    174 

/opt/code/github/threefoldtech/0-robot/JumpscaleZrobot/clients/zerorobot/client/services_service.py in GetTask(self, task_guid, service_guid, headers, query_params, content_type)
     83                                     message=message)
     84         except ValueError as msg:
---> 85             raise UnmarshallError(resp, msg)
     86         except UnhandledAPIError as uae:
     87             raise uae

UnmarshallError: (<Response [200]>, ValueError('Task: unable to create eco from value: {\'cat\': \'python.requests.exceptions.HTTPError\', \'count\': 1, \'message\': \'500 Server Error: Internal Server Error for url: http://10.10.111.251:92/restmachine/zrobot/client/delete\', \'message_pub\': \'\', \'time_first\': 0, \'time_last\': 0, \'trace\': \'Traceback (most recent call last):\\n  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 76, in execute\\n    self._result = self._func(**self._args)\\n  File "/opt/code/github/threefoldtech/0-templates/templates/portal_connection/portal_connection.py", line 52, in uninstall\\n    resp.raise_for_status()\\n  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status\\n    raise HTTPError(http_error_msg, response=self)\\nrequests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.10.111.251:92/restmachine/zrobot/client/delete\\n\'}: val_factory: Unable to instantiate {\'cat\': \'python.requests.exceptions.HTTPError\', \'count\': 1, \'message\': \'500 Server Error: Internal Server Error for url: http://10.10.111.251:92/restmachine/zrobot/client/delete\', \'message_pub\': \'\', \'time_first\': 0, \'time_last\': 0, \'trace\': \'Traceback (most recent call last):\\n  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 76, in execute\\n    self._result = self._func(**self._args)\\n  File "/opt/code/github/threefoldtech/0-templates/templates/portal_connection/portal_connection.py", line 52, in uninstall\\n    resp.raise_for_status()\\n  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status\\n    raise HTTPError(http_error_msg, response=self)\\nrequests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.10.111.251:92/restmachine/zrobot/client/delete\\n\'} from types [<class \'JumpscaleZrobot.clients.zerorobot.client.Eco.Eco\'>]. Exceptions: [\'Eco: missing required property _limit\']',))
```

**EDIT**

It might be caused because of a mongoDB error (`NotMasterError`), trying to verify atm

**Comment by chrisvdg** [comment]
Fixed the mongoDB error, will reconfirm in a few days if the robot-portal is still running nominally

**Comment by chrisvdg** [comment]
Robot is still visible in the portal
